update go.mod dependencies and Makefile based on latest crossplane st…
linode/provider-linode pull request #27
Opened 2023-11-16 20:53 UTC by eljohnson92

…andards

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2023-11-16 21:00 UTC, schinmai-akamai requested changes

2023-11-17 16:16 UTC, srust approved these changes
LGTM!

2023-11-17 16:20 UTC, schinmai-akamai commented on Makefile
> +XPKG_REG_ORGS_NO_PROMOTE ?= xpkg.upbound.io/upbound
Should this be upbound? And not linode?

2023-11-17 16:23 UTC, schinmai-akamai commented on cmd/provider/main.go
> +		essTLSCertsPath            = app.Flag("ess-tls-cert-dir", "Path of ESS TLS certificates.").Envar("ESS_TLS_CERTS_DIR").String()
What’s a ess cert?

2024-02-12 22:23 UTC, tchinmai7 approved these changes

2024-02-12 22:31 UTC, merged